/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ims.gui;

import ims.bll.*;
import ims.dto.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NAT
 */
public class EmployeeList extends javax.swing.JFrame {

    List<Employee> empList;
    List<Bangcap> bcList;
    List<Chucvu> cvList;
    List<Congviec> viecList;
    List<Dantoc> dtList;
    List<Gioitinh> gtList;
    List<Hocvan> hvList;
    List<Loainhanvien> lnvList;
    List<Ngoaingu> nnList;
    List<Phongban> pbList;
    List<Quoctich> qtList;
    List<Tinhhoc> thList;
    List<Tinhthanh> ttList;
    List<Tongiao> tgList;

    EmployeeBLL empBLL;
    BangcapBLL bcBLL;
    ChucvuBLL cvBLL;
    CongviecBLL viecBLL;
    DantocBLL dtBLL;
    GioitinhBLL gtBLL;
    HocvanBLL hvBLL;
    LoainhanvienBLL lnvBll;
    NgoainguBLL nnBLL;
    PhongbanBLL pbBLL;
    QuoctichBLL qtBLL;
    TinhhocBLL thBLL;
    TinhthanhBLL ttBLL;
    TongiaoBLL tgbBLL;

    /**
     * Creates new form EmployeeList
     */
    public EmployeeList() {
        initComponents();
        setInfoDialog();
        empBLL = new EmployeeBLL();
        bcBLL = new BangcapBLL();
        cvBLL = new ChucvuBLL();
        viecBLL = new CongviecBLL();
        dtBLL = new DantocBLL();
        hvBLL = new HocvanBLL();
        gtBLL = new GioitinhBLL();
        lnvBll = new LoainhanvienBLL();
        nnBLL = new NgoainguBLL();
        pbBLL = new PhongbanBLL();
        qtBLL = new QuoctichBLL();
        thBLL = new TinhhocBLL();
        ttBLL = new TinhthanhBLL();
        tgbBLL = new TongiaoBLL();
    }

    public void setInfoDialog() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btNew = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btEdit = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btDelete = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmployee = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        btNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ims/images/47.png"))); // NOI18N
        btNew.setText("Thêm nhân viên ");
        btNew.setFocusable(false);
        btNew.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btNew);
        jToolBar1.add(jSeparator1);

        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ims/images/48.png"))); // NOI18N
        btEdit.setText("Sửa nhân viên");
        btEdit.setBorderPainted(false);
        btEdit.setFocusable(false);
        btEdit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });
        jToolBar1.add(btEdit);
        jToolBar1.add(jSeparator2);

        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ims/images/46.png"))); // NOI18N
        btDelete.setText("Xóa nhân viên");
        btDelete.setFocusable(false);
        btDelete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        jToolBar1.add(btDelete);
        jToolBar1.add(jSeparator3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ims/images/printSmall.png"))); // NOI18N
        jButton4.setText("In nhân viên");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ims/images/Exit.png"))); // NOI18N
        jButton5.setText("Thoát");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        tbEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Họ Tên", "Bí Danh", "Giới Tính", "Di Động", "Điện Thoại Nhà", "Email", "Ngày Sinh", "Nơi Sinh", "Tỉnh Thành"
            }
        ));
        jScrollPane1.setViewportView(tbEmployee);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 Employee employeeToEdit;
    private void btNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewActionPerformed
        IfEmployee emGui = new IfEmployee(this);
       // emGui.setLisDepartment(depList);
        emGui.setListBangcap(bcList);
            emGui.setListChucvu(cvList);
            emGui.setListCongviec(viecList);
            emGui.setListDantoc(dtList);
            emGui.setListHocvan(hvList);
            emGui.setListGioitinh(gtList);
            emGui.setListLoainhanvien(lnvList);
            emGui.setListNgoaingu(nnList);
            emGui.setListPhongban(pbList);
            emGui.setListQuoctich(qtList);
            emGui.setListTinhhoc(thList);
            emGui.setListTinhthanh(ttList);
            emGui.setListTongiao(tgList);
        emGui.setVisible(true);

        Employee newEmployee = emGui.getEmployee();

        if (newEmployee != null) {
            try {
                empBLL.save(newEmployee);
                empList.add(newEmployee);
                
                DefaultTableModel model = (DefaultTableModel) tbEmployee.getModel();
                int newRow = tbEmployee.getRowCount();
                model.addRow(new Object[0]);
                updateTableEmployee(newEmployee, newRow);
                
            } catch (Exception ex) {
                String message = "Could not save new employee. Error:\n" + ex.getMessage();
                JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        

    }//GEN-LAST:event_btNewActionPerformed
    private void updateTableEmployee(Employee employee, int row) {
        DefaultTableModel model = (DefaultTableModel) tbEmployee.getModel();
        model.setValueAt(employee.getMaNV(), row, 0);
        model.setValueAt(employee.getHoten(), row, 1);
        model.setValueAt(employee.getBidanh(), row, 2);
        model.setValueAt(employee.getGioitinh().getTengioitinh(), row, 3);

        model.setValueAt(employee.getDidong(), row, 4);
        model.setValueAt(employee.getDienthoainha(), row, 5);
        model.setValueAt(employee.getDiachiemail(), row, 6);
        model.setValueAt(employee.getNgaysinh(), row, 7);

        model.setValueAt(employee.getNoisinh(), row, 8);
        model.setValueAt(employee.getTinhthanh().getTentinhthanh(), row, 9);
//        model.setValueAt(employee.getCMND(), row, 10);
//        model.setValueAt(employee.getNgaycap(), row, 11);
//
//        model.setValueAt(employee.getNoicap(), row, 12);
//        model.setValueAt(employee.getQuequan(), row, 13);
//        model.setValueAt(employee.getDiachi(), row, 14);
//        model.setValueAt(employee.getTamtru(), row, 15);
//
//        model.setValueAt(employee.getLoainhanvien().getTenloainv(), row, 16);
//        model.setValueAt(employee.getNgayvaolam(), row, 17);
//        model.setValueAt(employee.getPhongban().getTenphongban(), row, 18);
//        model.setValueAt(employee.getCongviec().getTencongviec(), row, 19);
//
//        model.setValueAt(employee.getChucvu().getTenchucvu(), row, 20);
//        model.setValueAt(employee.getMucluongcb(), row, 21);
//        model.setValueAt(employee.getHeso(), row, 22);
//        model.setValueAt(employee.getMucluong(), row, 23);
//
//        model.setValueAt(employee.getPhucapluong(), row, 24);
//        model.setValueAt(employee.getSosolaodong(), row, 25);
//        model.setValueAt(employee.getNgaycapsld(), row, 26);
//        model.setValueAt(employee.getNoicapsld(), row, 27);
//
//        model.setValueAt(employee.getTknganhang(), row, 28);
//        model.setValueAt(employee.getNganhang(), row, 29);
//        model.setValueAt(employee.getHocvan().getTenhocvan(), row, 30);
//        model.setValueAt(employee.getBangcap().getTenbangcap(), row, 31);
//
//        model.setValueAt(employee.getNgoaingu().getTenngoaingu(), row, 32);
//        model.setValueAt(employee.getTinhhoc().getTentinhoc(), row, 33);
//        model.setValueAt(employee.getDantoc().getTendantoc(), row, 34);
//        model.setValueAt(employee.getQuoctich().getTenquoctich(), row, 35);
//
//        model.setValueAt(employee.getTongiao().getTentongiao(), row, 36);
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        empList = empBLL.listAll();
        bcList = bcBLL.listAll();
        cvList = cvBLL.listAll();
        viecList = viecBLL.listAll();
        dtList = dtBLL.listAll();
        hvList = hvBLL.listAll();
        gtList = gtBLL.listAll();
        lnvList = lnvBll.listAll();
        nnList = nnBLL.listAll();
        pbList = pbBLL.listAll();
        qtList = qtBLL.listAll();
        thList = thBLL.listAll();
        ttList = ttBLL.listAll();
        tgList = tgbBLL.listAll();
        DefaultTableModel model = (DefaultTableModel) tbEmployee.getModel();
        int row = 0;
        for (Iterator iterator = empList.iterator(); iterator.hasNext();) {
            Employee emp = (Employee) iterator.next();
            model.addRow(new Object[0]);
            updateTableEmployee(emp, row);
            row++;
        }
    }//GEN-LAST:event_formWindowOpened

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbEmployee.getSelectedRow();

        IfEmployee emGui = new IfEmployee(this);
        if (selectedRow >= 0) {
            employeeToEdit = empList.get(selectedRow);
            emGui.setListBangcap(bcList);
            emGui.setListChucvu(cvList);
            emGui.setListCongviec(viecList);
            emGui.setListDantoc(dtList);
            emGui.setListHocvan(hvList);
            emGui.setListGioitinh(gtList);
            emGui.setListLoainhanvien(lnvList);
            emGui.setListNgoaingu(nnList);
            emGui.setListPhongban(pbList);
            emGui.setListQuoctich(qtList);
            emGui.setListTinhhoc(thList);
            emGui.setListTinhthanh(ttList);
            emGui.setListTongiao(tgList);
            emGui.setEmployee(employeeToEdit);
            emGui.setVisible(true);
        }

        Employee editedEmployee = emGui.getEmployee();

        if (editedEmployee != null) {
            try {
                empBLL.save(editedEmployee);
                updateTableEmployee(editedEmployee, selectedRow);
            } catch (Exception ex) {
                String message = "Could not update Employee. Error:\n" + ex.getMessage();
                JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btEditActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        Employee employeeToDelete ;
        try {
            int selectedRow = tbEmployee.getSelectedRow();
            if (selectedRow >= 0) {
                employeeToDelete = empList.get(selectedRow);                		
		if (employeeToDelete != null) {
                    String message = String.format( "Do you really want to delete '%s'?", employeeToDelete.getHoten()); 
                    int answer = JOptionPane.showConfirmDialog(this, message, "Confirmation", JOptionPane.YES_NO_OPTION);
                    if (answer == JOptionPane.OK_OPTION) {                                
                        empBLL.delete(employeeToDelete);
                        empList.remove(employeeToDelete);
                        DefaultTableModel model =(DefaultTableModel)tbEmployee.getModel();
                        model.removeRow(selectedRow);
                    }
                }
            }
        } catch (Exception ex) {
            String message = "Could not delete category. Error:\n"+ ex.getMessage();
            JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btNew;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbEmployee;
    // End of variables declaration//GEN-END:variables

}
